### ISSUE TITLE
Question.

### ISSUE THREAD

**Issue by Gamemulatorer** [tytydraco/ktweak#1]
How doI know if your tweaks is really working on my phone? there's a log? sorry for my english :)

**Comment by tytydraco** [comment]
Hi!

By default, ktweak does not print logging information. You can run ktweak manually with `ktweak -d` to view all of the logs, so you can see that they are properly applying. You may see a few warnings about some tunables not applying, but that is completely normal, as not all devices have the same tunables.

Hope this helps! Feel free to re-open this issue if you have more questions.
