### ISSUE TITLE
Why there are no releases?

### ISSUE THREAD

**Issue by pkejval** [tytydraco/KTweak#5]
Hello, why there are no releases? They used to be there and I used it to install new versions. How are we supposed to install KTweak now?

**Comment by ghostrider-reborn** [comment]
> Hello, why there are no releases? They used to be there and I used it to install new versions. How are we supposed to install KTweak now?

https://play.google.com/store/apps/details?id=com.draco.ktweak

**Comment by pkejval** [comment]
Thanks! 👍
