### ISSUE TITLE
Are swappiness settings ok?

### ISSUE THREAD

**Issue by dim-geo** [tytydraco/KTweak#7]
Maybe you mean to write 80 as said in xda thread?

https://forum.xda-developers.com/android/software/module-ktweak-evidence-t4148447

https://github.com/tytydraco/KTweak/blob/0e43c297cfe13c04f8dc36a0f1607b4e26c366fc/ktweak#L117

**Comment by tytydraco** [comment]
Hi! The XDA article is pretty outdated. It is correct.
